[package]
name = "venues"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
# Internal dependencies
websockets = { path = "../websockets" }

# External dependencies
tokio.workspace = true
tokio-tungstenite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
reqwest.workspace = true
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
chrono.workspace = true
url.workspace = true
futures.workspace = true
async-trait.workspace = true
parking_lot.workspace = true
tracing.workspace = true
ratatui = { workspace = true }
crossterm = { workspace = true }
rust_decimal.workspace = true
dotenv = "0.15"
thiserror.workspace = true
clap.workspace = true
aes-gcm = "0.10.3"
base64 = "0.22.1"
rand = "0.9.1"
secrecy = "0.10.3"

[lints]
workspace = true

[[example]]
name = "coinbase_market_data"
path = "examples/coinbase_market_data/coinbase_market_data.rs"

[[example]]
name = "authenticated_websocket"
path = "examples/authenticated_websocket/authenticated_websocket.rs"

[dev-dependencies]
tokio = { workspace = true, features = ["full", "macros"] }
tracing-subscriber = { workspace = true }
