[workspace]
resolver = "2"
members = [ "orderbook",
    "venues"
, "websockets"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = []
license = "MIT"
repository = "https://github.com/rosssaunders/ccrxt"
description = "High performance Rust client for cryptocurrency exchanges"

[workspace.dependencies]
# Async runtime
tokio = { version = "1.28", features = ["full"] }
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"

# Error handling
thiserror = "2.0.12"
anyhow = "1.0"

# HTTP client
reqwest = { version = "0.12.14", features = ["json", "native-tls"] }

# Crypto and auth
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"

# Utilities
chrono = { version = "0.4", features = ["serde"] }
url = "2.4"
futures = "0.3"
async-trait = "0.1"
parking_lot = "0.12"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# New dependencies
ratatui = "0.26.1"
crossterm = "0.28.1"

[workspace.lints.rust]
unsafe_code = "forbid"
