[package]
name = "pagination"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Generic async paginator for API endpoints"

[dependencies]

[lints]
workspace = true
