name: Run Claude Command to Update API Errors

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run_claude_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Recommended for some git operations, good to have

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Claude Code CLI
        run: npm install -g @anthropic-ai/claude-code

      - name: Run Claude command and capture output
        id: claude_run
        run: |
          set -x
          export ANTHROPIC_API_KEY=${{ secrets.CLAUDE_ANTHROPIC_API_KEY }}
          npx claude -p "add a new api error to binance coinm: -5000 Invalid Margin Parameter" --allowedTools "Bash(git:*),Edit" --output-format json > claude_output.json
          # If claude_output.json is empty or not created, create a dummy file with an error message
          if [ ! -s claude_output.json ]; then
            echo "Warning: claude_output.json is empty or was not created by the claude command."
            echo '{"result": "Claude command did not produce the expected output file (claude_output.json was empty or not found). Please check the workflow logs and the claude-output artifact."}' > claude_output.json
          fi
        env:
          # IMPORTANT: Configure this secret in your GitHub repository settings
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_ANTHROPIC_API_KEY }}
        shell: bash

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        shell: bash

      - name: Prepare PR Body File
        id: prepare_pr_body
        run: |
          jq -r '.result // "Failed to extract result from Claude output. Please check claude_output.json artifact or workflow logs."' claude_output.json > pr_body.md
          # Fallback if pr_body.md somehow wasn't created (e.g. jq error not caught by shell)
          if [ ! -f pr_body.md ]; then
            echo "Error: pr_body.md was not created during jq processing."
            echo "Failed to extract result from Claude output. Please check claude_output.json artifact or workflow logs." > pr_body.md
          fi
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Uses the default GITHUB_TOKEN
          commit-message: "Apply Claude updates for API errors (-5000 Invalid Margin Parameter)"
          title: "Claude AI Update: Add Binance COIN-M API Error -5000 Invalid Margin Parameter"
          body-path: pr_body.md # Path to the file containing the PR body
          branch: claude/update-api-errors # Base name for the branch
          branch-suffix: timestamp # Appends a timestamp to make the branch unique, e.g., claude/update-api-errors-1618033200
          delete-branch: true # Deletes the branch once the PR is merged
          # Optional: Add labels, assignees, reviewers if needed
          # labels: claude-update, api-error
          # assignees: ${{ github.actor }}

      - name: Upload Claude output artifact
        uses: actions/upload-artifact@v4
        if: always() # Run even if previous steps fail
        with:
          name: claude-output
          path: |
            claude_output.json
            pr_body.md
